-- JIGME TENZIN ePORTFOLIO - SAFE INSTALL / MIGRATION
-- This script is designed for an existing project too.
-- RLS stays ENABLED. Run the whole file in a NEW SQL Editor query.

create table if not exists portfolio_profile(id bigint generated by default as identity primary key,name text not null,intro text,profile_image text,cv_url text,contact_email text,contact_phone text,updated_at timestamptz default now());
create table if not exists portfolio_skills(id bigint generated by default as identity primary key,name text not null,description text,level integer default 75 check(level between 0 and 100),icon text default '✨',color text default '#22d3ee',image_url text,video_url text,gallery text,display_order integer default 0);
create table if not exists portfolio_education(id bigint generated by default as identity primary key,period text not null,title text not null,institution text,description text,image_url text,video_url text,certificate_url text,gallery text,display_order integer default 0);
create table if not exists portfolio_about(id bigint generated by default as identity primary key,content text not null,content_before text,content_middle text,content_after text,image_url text,video_url text,gallery text,updated_at timestamptz default now());
create table if not exists portfolio_projects(id bigint generated by default as identity primary key,title text not null,description text,tech text,technologies text,image_url text,project_url text,github_url text,icon text default '✦',video_url text,gallery text,display_order integer default 0,created_at timestamptz default now());
create table if not exists portfolio_socials(id bigint generated by default as identity primary key,name text not null,url text not null,icon text default '↗',display_order integer default 0);
create table if not exists portfolio_messages(id bigint generated by default as identity primary key,name text not null,email text not null,message text not null,created_at timestamptz default now(),is_read boolean default false);
create table if not exists portfolio_admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz default now());

alter table portfolio_about add column if not exists content_before text;
alter table portfolio_about add column if not exists content_middle text;
alter table portfolio_about add column if not exists content_after text;
alter table portfolio_about add column if not exists image_url text;
alter table portfolio_about add column if not exists video_url text;
alter table portfolio_about add column if not exists gallery text;

-- Migrate older project-table versions safely.
alter table portfolio_profile add column if not exists profile_image text;
alter table portfolio_profile add column if not exists cv_url text;
alter table portfolio_profile add column if not exists contact_email text;
alter table portfolio_profile add column if not exists contact_phone text;
alter table portfolio_skills add column if not exists color text default '#22d3ee';
alter table portfolio_projects add column if not exists tech text;
alter table portfolio_projects add column if not exists technologies text;
alter table portfolio_projects add column if not exists image_url text;
alter table portfolio_projects add column if not exists project_url text;
alter table portfolio_projects add column if not exists github_url text;
alter table portfolio_projects add column if not exists icon text default '✦';
alter table portfolio_projects add column if not exists display_order integer default 0;
alter table portfolio_projects add column if not exists created_at timestamptz default now();

alter table portfolio_skills add column if not exists image_url text;
alter table portfolio_skills add column if not exists video_url text;
alter table portfolio_skills add column if not exists gallery text;
alter table portfolio_education add column if not exists image_url text;
alter table portfolio_education add column if not exists video_url text;
alter table portfolio_education add column if not exists certificate_url text;
alter table portfolio_education add column if not exists gallery text;
alter table portfolio_projects add column if not exists video_url text;
alter table portfolio_projects add column if not exists gallery text;


alter table portfolio_profile enable row level security;
alter table portfolio_skills enable row level security;
alter table portfolio_education enable row level security;
alter table portfolio_about enable row level security;
alter table portfolio_projects enable row level security;
alter table portfolio_socials enable row level security;
alter table portfolio_messages enable row level security;
alter table portfolio_admins enable row level security;

-- Public read policies for portfolio content.
drop policy if exists "portfolio profile public read" on portfolio_profile;
create policy "portfolio profile public read" on portfolio_profile for select to anon,authenticated using(true);
drop policy if exists "portfolio skills public read" on portfolio_skills;
create policy "portfolio skills public read" on portfolio_skills for select to anon,authenticated using(true);
drop policy if exists "portfolio education public read" on portfolio_education;
create policy "portfolio education public read" on portfolio_education for select to anon,authenticated using(true);
drop policy if exists "portfolio about public read" on portfolio_about;
create policy "portfolio about public read" on portfolio_about for select to anon,authenticated using(true);
drop policy if exists "portfolio projects public read" on portfolio_projects;
create policy "portfolio projects public read" on portfolio_projects for select to anon,authenticated using(true);
drop policy if exists "portfolio socials public read" on portfolio_socials;
create policy "portfolio socials public read" on portfolio_socials for select to anon,authenticated using(true);

-- Contact form: anyone can submit, nobody can read through the public anon key.
drop policy if exists "portfolio messages public insert" on portfolio_messages;
create policy "portfolio messages public insert" on portfolio_messages for insert to anon,authenticated with check(true);
drop policy if exists "portfolio messages admin read" on portfolio_messages;
create policy "portfolio messages admin read" on portfolio_messages for select to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));

-- Admin table: users can see only their own admin record.
drop policy if exists "portfolio admins self read" on portfolio_admins;
create policy "portfolio admins self read" on portfolio_admins for select to authenticated using(user_id=auth.uid());

-- Authenticated admins can edit portfolio content.
drop policy if exists "portfolio profile admin write" on portfolio_profile;
create policy "portfolio profile admin write" on portfolio_profile for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio skills admin write" on portfolio_skills;
create policy "portfolio skills admin write" on portfolio_skills for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio education admin write" on portfolio_education;
create policy "portfolio education admin write" on portfolio_education for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio about admin write" on portfolio_about;
create policy "portfolio about admin write" on portfolio_about for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio projects admin write" on portfolio_projects;
create policy "portfolio projects admin write" on portfolio_projects for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio socials admin write" on portfolio_socials;
create policy "portfolio socials admin write" on portfolio_socials for all to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio messages admin update" on portfolio_messages;
create policy "portfolio messages admin update" on portfolio_messages for update to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid())) with check(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));
drop policy if exists "portfolio messages admin delete" on portfolio_messages;
create policy "portfolio messages admin delete" on portfolio_messages for delete to authenticated using(exists(select 1 from portfolio_admins a where a.user_id=auth.uid()));

-- Seed content only when the corresponding table is empty.
insert into portfolio_profile(name,intro) select 'Jigme Tenzin','A teacher trainee exploring technology, programming, web development and creative digital solutions.' where not exists(select 1 from portfolio_profile);
insert into portfolio_about(content) select 'I am Jigme Tenzin, a teacher trainee with a strong interest in Information Technology, digital tools and creative problem-solving.

I enjoy learning by building practical projects and exploring ways technology can make everyday tasks simpler and learning more engaging.

My interests include web development, programming, ICT education, football, hiking and continuous self-improvement. This ePortfolio represents my learning journey and the things I am working towards.' where not exists(select 1 from portfolio_about);
insert into portfolio_skills(name,description,level,icon,color,display_order) select * from (values ('Web Development','Responsive websites with HTML, CSS and JavaScript.',88,'🌐','#25d9ff',1),('Python Programming','Programming, algorithms and practical problem solving.',82,'🐍','#facc15',2),('Database & Supabase','SQL, cloud data and modern web backends.',78,'🗄️','#34d399',3),('UI & UX Design','Clean, colorful and user-friendly interfaces.',80,'🎨','#ff4ecd',4),('ICT Teaching','Interactive technology learning and lesson design.',86,'👨‍🏫','#8c6cff',5),('Problem Solving','Breaking ideas into clear, practical steps.',84,'🧩','#60a5fa',6)) v(name,description,level,icon,color,display_order) where not exists(select 1 from portfolio_skills);
insert into portfolio_education(period,title,institution,description,display_order) select * from (values ('2023 — 2027','B.Ed. IT / Digital Technology & Innovation','Samtse College of Education, Royal University of Bhutan','ICT, programming, pedagogy and educational innovation.',1),('2017 — 2022','Class 7 — 12, Arts Stream','Minjiwoong Higher Secondary School','Secondary education with continued interest in technology.',2),('2008 — 2016','Grade PP — 6','Lauri Primary School','Foundation for lifelong learning and curiosity.',3)) v(period,title,institution,description,display_order) where not exists(select 1 from portfolio_education);
insert into portfolio_projects(title,description,tech,technologies,icon,display_order) select * from (values ('QR Restaurant Ordering System','A responsive restaurant ordering platform with QR-based table access, Supabase data and separate customer/admin experiences.','HTML · CSS · JavaScript · Supabase','HTML · CSS · JavaScript · Supabase','🍽️',1),('School Management System','A digital school dashboard covering students, teachers, results, attendance, admission and notices.','Supabase · JavaScript · Vercel','Supabase · JavaScript · Vercel','🏫',2),('EVMS','A desktop electronic voting management system with nominees, voters, voting and reports.','Python · Tkinter · SQLite','Python · Tkinter · SQLite','🗳️',3),('Library Management System','A school library system for registration, borrowing and due-book tracking.','Python · Tkinter · SQLite','Python · Tkinter · SQLite','📚',4)) v(title,description,tech,technologies,icon,display_order) where not exists(select 1 from portfolio_projects);
insert into portfolio_socials(name,url,icon,display_order) select * from (values ('GitHub','https://github.com/','⌘',1),('YouTube','https://www.youtube.com/','▶',2),('LinkedIn','https://www.linkedin.com/','in',3)) v(name,url,icon,display_order) where not exists(select 1 from portfolio_socials);

-- ================= IMAGE UPLOADS (Storage) =================
-- One public bucket holds every uploaded image (profile photo, skill icons,
-- project images, social icons). Public can only READ; only a signed-in
-- admin (present in portfolio_admins) can upload/replace/delete.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('portfolio-media','portfolio-media', true, 52428800, ARRAY['image/*','video/*','application/pdf'])
  on conflict (id) do update set public = true, file_size_limit = 52428800, allowed_mime_types = ARRAY['image/*','video/*','application/pdf'];

drop policy if exists "portfolio media public read" on storage.objects;
create policy "portfolio media public read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'portfolio-media');

drop policy if exists "portfolio media admin insert" on storage.objects;
create policy "portfolio media admin insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'portfolio-media' and exists(select 1 from portfolio_admins a where a.user_id = auth.uid()));

drop policy if exists "portfolio media admin update" on storage.objects;
create policy "portfolio media admin update" on storage.objects
  for update to authenticated
  using (bucket_id = 'portfolio-media' and exists(select 1 from portfolio_admins a where a.user_id = auth.uid()))
  with check (bucket_id = 'portfolio-media' and exists(select 1 from portfolio_admins a where a.user_id = auth.uid()));

drop policy if exists "portfolio media admin delete" on storage.objects;
create policy "portfolio media admin delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'portfolio-media' and exists(select 1 from portfolio_admins a where a.user_id = auth.uid()));

-- ADMIN SETUP:
-- 1) Create your admin user in Supabase Authentication > Users.
-- 2) Copy that user's UUID.
-- 3) Run: insert into portfolio_admins(user_id) values('YOUR-USER-UUID');
-- 4) If "Add/Edit/Delete" ever silently fails for ANY section (Skills,
--    Social Links, etc.), it is almost always this step: that logged-in
--    user's UUID is missing from portfolio_admins. Re-run step 3.
